<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Banks', 'hekphone');

/**
 * BaseBanks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $validator
 * @property integer $mainagency
 * @property Doctrine_Collection $Agencys
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getValidator()  Returns the current record's "validator" value
 * @method integer             getMainagency() Returns the current record's "mainagency" value
 * @method Doctrine_Collection getAgencys()    Returns the current record's "Agencys" collection
 * @method Banks               setId()         Sets the current record's "id" value
 * @method Banks               setValidator()  Sets the current record's "validator" value
 * @method Banks               setMainagency() Sets the current record's "mainagency" value
 * @method Banks               setAgencys()    Sets the current record's "Agencys" collection
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBanks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bav_bank');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'unique' => true,
             'length' => 8,
             ));
        $this->hasColumn('validator', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('mainagency', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Agencys', array(
             'local' => 'id',
             'foreign' => 'bank'));
    }
}