<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Calls', 'hekphone');

/**
 * BaseCalls
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $resident
 * @property integer $extension
 * @property timestamp $date
 * @property integer $duration
 * @property string $destination
 * @property decimal $charges
 * @property integer $rate
 * @property integer $bill
 * @property Residents $Residents
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getResident()    Returns the current record's "resident" value
 * @method integer   getExtension()   Returns the current record's "extension" value
 * @method timestamp getDate()        Returns the current record's "date" value
 * @method integer   getDuration()    Returns the current record's "duration" value
 * @method string    getDestination() Returns the current record's "destination" value
 * @method decimal   getCharges()     Returns the current record's "charges" value
 * @method integer   getRate()        Returns the current record's "rate" value
 * @method integer   getBill()        Returns the current record's "bill" value
 * @method Residents getResidents()   Returns the current record's "Residents" value
 * @method Calls     setId()          Sets the current record's "id" value
 * @method Calls     setResident()    Sets the current record's "resident" value
 * @method Calls     setExtension()   Sets the current record's "extension" value
 * @method Calls     setDate()        Sets the current record's "date" value
 * @method Calls     setDuration()    Sets the current record's "duration" value
 * @method Calls     setDestination() Sets the current record's "destination" value
 * @method Calls     setCharges()     Sets the current record's "charges" value
 * @method Calls     setRate()        Sets the current record's "rate" value
 * @method Calls     setBill()        Sets the current record's "bill" value
 * @method Calls     setResidents()   Sets the current record's "Residents" value
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCalls extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('calls');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'calls_id',
             ));
        $this->hasColumn('resident', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('extension', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             'default' => 'now()',
             ));
        $this->hasColumn('duration', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('destination', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('charges', 'decimal', 18, array(
             'type' => 'decimal',
             'notnull' => true,
             'length' => 18,
             ));
        $this->hasColumn('rate', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('bill', 'integer', null, array(
             'type' => 'integer',
             'default' => '0',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Residents', array(
             'local' => 'resident',
             'foreign' => 'id'));
    }
}