<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rates', 'hekphone');

/**
 * BaseRates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $provider
 * @property time $primary_time_begin
 * @property decimal $primary_time_rate
 * @property time $secondary_time_begin
 * @property decimal $secondary_time_rate
 * @property boolean $weekend
 * @property boolean $week
 * @property enum $pulsing
 * @property string $name
 * @property Doctrine_Collection $RatesRegions
 * @property Providers $Providers
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method integer             getProvider()             Returns the current record's "provider" value
 * @method time                getPrimaryTimeBegin()     Returns the current record's "primary_time_begin" value
 * @method decimal             getPrimaryTimeRate()      Returns the current record's "primary_time_rate" value
 * @method time                getSecondaryTimeBegin()   Returns the current record's "secondary_time_begin" value
 * @method decimal             getSecondaryTimeRate()    Returns the current record's "secondary_time_rate" value
 * @method boolean             getWeekend()              Returns the current record's "weekend" value
 * @method boolean             getWeek()                 Returns the current record's "week" value
 * @method enum                getPulsing()              Returns the current record's "pulsing" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method Doctrine_Collection getRatesRegions()         Returns the current record's "RatesRegions" collection
 * @method Providers           getProviders()            Returns the current record's "Providers" value
 * @method Rates               setId()                   Sets the current record's "id" value
 * @method Rates               setProvider()             Sets the current record's "provider" value
 * @method Rates               setPrimaryTimeBegin()     Sets the current record's "primary_time_begin" value
 * @method Rates               setPrimaryTimeRate()      Sets the current record's "primary_time_rate" value
 * @method Rates               setSecondaryTimeBegin()   Sets the current record's "secondary_time_begin" value
 * @method Rates               setSecondaryTimeRate()    Sets the current record's "secondary_time_rate" value
 * @method Rates               setWeekend()              Sets the current record's "weekend" value
 * @method Rates               setWeek()                 Sets the current record's "week" value
 * @method Rates               setPulsing()              Sets the current record's "pulsing" value
 * @method Rates               setName()                 Sets the current record's "name" value
 * @method Rates               setRatesRegions()         Sets the current record's "RatesRegions" collection
 * @method Rates               setProviders()            Sets the current record's "Providers" value
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRates extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rates');
        $this->hasColumn('id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 6,
             ));
        $this->hasColumn('provider', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('primary_time_begin', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('primary_time_rate', 'decimal', 18, array(
             'type' => 'decimal',
             'notnull' => true,
             'length' => 18,
             ));
        $this->hasColumn('secondary_time_begin', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('secondary_time_rate', 'decimal', 18, array(
             'type' => 'decimal',
             'length' => 18,
             ));
        $this->hasColumn('weekend', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 'true',
             ));
        $this->hasColumn('week', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 'true',
             ));
        $this->hasColumn('pulsing', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '1/1',
              1 => '60/60',
              2 => '30/1',
              3 => '60/1',
              4 => '60/0',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RatesRegions', array(
             'local' => 'id',
             'foreign' => 'rate'));

        $this->hasOne('Providers', array(
             'local' => 'provider',
             'foreign' => 'id'));
    }
}