<?php

/**
 * BaseResidentsGroupcalls
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $resident_id
 * @property integer $groupcall_id
 * 
 * @method integer             getResidentId()   Returns the current record's "resident_id" value
 * @method integer             getGroupcallId()  Returns the current record's "groupcall_id" value
 * @method ResidentsGroupcalls setResidentId()   Sets the current record's "resident_id" value
 * @method ResidentsGroupcalls setGroupcallId()  Sets the current record's "groupcall_id" value
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResidentsGroupcalls extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('residents_groupcalls');
        $this->hasColumn('resident_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('groupcall_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}