<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Providers', 'hekphone');

/**
 * BaseProviders
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Rates
 * 
 * @method integer             getId()    Returns the current record's "id" value
 * @method string              getName()  Returns the current record's "name" value
 * @method Doctrine_Collection getRates() Returns the current record's "Rates" collection
 * @method Providers           setId()    Sets the current record's "id" value
 * @method Providers           setName()  Sets the current record's "name" value
 * @method Providers           setRates() Sets the current record's "Rates" collection
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProviders extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('providers');
        $this->hasColumn('id', 'integer', 1, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 1,
             ));
        $this->hasColumn('name', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Rates', array(
             'local' => 'id',
             'foreign' => 'provider'));
    }
}