<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Agencys', 'hekphone');

/**
 * BaseAgencys
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $postcode
 * @property string $city
 * @property string $shortterm
 * @property integer $bank
 * @property string $pan
 * @property string $bic
 * @property Banks $Banks
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getName()      Returns the current record's "name" value
 * @method string  getPostcode()  Returns the current record's "postcode" value
 * @method string  getCity()      Returns the current record's "city" value
 * @method string  getShortterm() Returns the current record's "shortterm" value
 * @method integer getBank()      Returns the current record's "bank" value
 * @method string  getPan()       Returns the current record's "pan" value
 * @method string  getBic()       Returns the current record's "bic" value
 * @method Banks   getBanks()     Returns the current record's "Banks" value
 * @method Agencys setId()        Sets the current record's "id" value
 * @method Agencys setName()      Sets the current record's "name" value
 * @method Agencys setPostcode()  Sets the current record's "postcode" value
 * @method Agencys setCity()      Sets the current record's "city" value
 * @method Agencys setShortterm() Sets the current record's "shortterm" value
 * @method Agencys setBank()      Sets the current record's "bank" value
 * @method Agencys setPan()       Sets the current record's "pan" value
 * @method Agencys setBic()       Sets the current record's "bic" value
 * @method Agencys setBanks()     Sets the current record's "Banks" value
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgencys extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bav_agency');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'unique' => true,
             ));
        $this->hasColumn('name', 'string', 58, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 58,
             ));
        $this->hasColumn('postcode', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('city', 'string', 35, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 35,
             ));
        $this->hasColumn('shortterm', 'string', 27, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 27,
             ));
        $this->hasColumn('bank', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pan', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('bic', 'string', 11, array(
             'type' => 'string',
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Banks', array(
             'local' => 'bank',
             'foreign' => 'id'));
    }
}