<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rooms', 'hekphone');

/**
 * BaseRooms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $room_no
 * @property string $comment
 * @property integer $phone
 * @property Phones $Phones
 * @property Doctrine_Collection $Residents
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method integer             getRoomNo()    Returns the current record's "room_no" value
 * @method string              getComment()   Returns the current record's "comment" value
 * @method integer             getPhone()     Returns the current record's "phone" value
 * @method Phones              getPhones()    Returns the current record's "Phones" value
 * @method Doctrine_Collection getResidents() Returns the current record's "Residents" collection
 * @method Rooms               setId()        Sets the current record's "id" value
 * @method Rooms               setRoomNo()    Sets the current record's "room_no" value
 * @method Rooms               setComment()   Sets the current record's "comment" value
 * @method Rooms               setPhone()     Sets the current record's "phone" value
 * @method Rooms               setPhones()    Sets the current record's "Phones" value
 * @method Rooms               setResidents() Sets the current record's "Residents" collection
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRooms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rooms');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'room_id',
             ));
        $this->hasColumn('room_no', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('phone', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Phones', array(
             'local' => 'phone',
             'foreign' => 'id'));

        $this->hasMany('Residents', array(
             'local' => 'id',
             'foreign' => 'room'));
    }
}