<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Phones', 'hekphone');

/**
 * BasePhones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $accountcode
 * @property string $callerid
 * @property string $canreinvite
 * @property string $host
 * @property integer $port
 * @property string $mailbox
 * @property string $md5secret
 * @property string $nat
 * @property string $permit
 * @property string $deny
 * @property string $mask
 * @property string $qualify
 * @property string $secret
 * @property string $type
 * @property string $username
 * @property string $defaultuser
 * @property string $useragent
 * @property string $fromuser
 * @property string $fromdomain
 * @property string $disallow
 * @property string $allow
 * @property string $ipaddr
 * @property string $mac
 * @property string $fullcontact
 * @property string $regexten
 * @property string $regserver
 * @property integer $regseconds
 * @property integer $lastms
 * @property Doctrine_Collection $Rooms
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getAccountcode() Returns the current record's "accountcode" value
 * @method string              getCallerid()    Returns the current record's "callerid" value
 * @method string              getCanreinvite() Returns the current record's "canreinvite" value
 * @method string              getHost()        Returns the current record's "host" value
 * @method integer             getPort()        Returns the current record's "port" value
 * @method string              getMailbox()     Returns the current record's "mailbox" value
 * @method string              getMd5secret()   Returns the current record's "md5secret" value
 * @method string              getNat()         Returns the current record's "nat" value
 * @method string              getPermit()      Returns the current record's "permit" value
 * @method string              getDeny()        Returns the current record's "deny" value
 * @method string              getMask()        Returns the current record's "mask" value
 * @method string              getQualify()     Returns the current record's "qualify" value
 * @method string              getSecret()      Returns the current record's "secret" value
 * @method string              getType()        Returns the current record's "type" value
 * @method string              getUsername()    Returns the current record's "username" value
 * @method string              getDefaultuser() Returns the current record's "defaultuser" value
 * @method string              getUseragent()   Returns the current record's "useragent" value
 * @method string              getFromuser()    Returns the current record's "fromuser" value
 * @method string              getFromdomain()  Returns the current record's "fromdomain" value
 * @method string              getDisallow()    Returns the current record's "disallow" value
 * @method string              getAllow()       Returns the current record's "allow" value
 * @method string              getIpaddr()      Returns the current record's "ipaddr" value
 * @method string              getMac()         Returns the current record's "mac" value
 * @method string              getFullcontact() Returns the current record's "fullcontact" value
 * @method string              getRegexten()    Returns the current record's "regexten" value
 * @method string              getRegserver()   Returns the current record's "regserver" value
 * @method integer             getRegseconds()  Returns the current record's "regseconds" value
 * @method integer             getLastms()      Returns the current record's "lastms" value
 * @method Doctrine_Collection getRooms()       Returns the current record's "Rooms" collection
 * @method Phones              setId()          Sets the current record's "id" value
 * @method Phones              setName()        Sets the current record's "name" value
 * @method Phones              setAccountcode() Sets the current record's "accountcode" value
 * @method Phones              setCallerid()    Sets the current record's "callerid" value
 * @method Phones              setCanreinvite() Sets the current record's "canreinvite" value
 * @method Phones              setHost()        Sets the current record's "host" value
 * @method Phones              setPort()        Sets the current record's "port" value
 * @method Phones              setMailbox()     Sets the current record's "mailbox" value
 * @method Phones              setMd5secret()   Sets the current record's "md5secret" value
 * @method Phones              setNat()         Sets the current record's "nat" value
 * @method Phones              setPermit()      Sets the current record's "permit" value
 * @method Phones              setDeny()        Sets the current record's "deny" value
 * @method Phones              setMask()        Sets the current record's "mask" value
 * @method Phones              setQualify()     Sets the current record's "qualify" value
 * @method Phones              setSecret()      Sets the current record's "secret" value
 * @method Phones              setType()        Sets the current record's "type" value
 * @method Phones              setUsername()    Sets the current record's "username" value
 * @method Phones              setDefaultuser() Sets the current record's "defaultuser" value
 * @method Phones              setUseragent()   Sets the current record's "useragent" value
 * @method Phones              setFromuser()    Sets the current record's "fromuser" value
 * @method Phones              setFromdomain()  Sets the current record's "fromdomain" value
 * @method Phones              setDisallow()    Sets the current record's "disallow" value
 * @method Phones              setAllow()       Sets the current record's "allow" value
 * @method Phones              setIpaddr()      Sets the current record's "ipaddr" value
 * @method Phones              setMac()         Sets the current record's "mac" value
 * @method Phones              setFullcontact() Sets the current record's "fullcontact" value
 * @method Phones              setRegexten()    Sets the current record's "regexten" value
 * @method Phones              setRegserver()   Sets the current record's "regserver" value
 * @method Phones              setRegseconds()  Sets the current record's "regseconds" value
 * @method Phones              setLastms()      Sets the current record's "lastms" value
 * @method Phones              setRooms()       Sets the current record's "Rooms" collection
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('phones');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'phone_id',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             ));
        $this->hasColumn('accountcode', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('callerid', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('canreinvite', 'string', null, array(
             'type' => 'string',
             'default' => 'yes',
             ));
        $this->hasColumn('host', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('port', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mailbox', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('md5secret', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('nat', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'no',
             ));
        $this->hasColumn('permit', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('deny', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('mask', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('qualify', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('secret', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'friend',
             ));
        $this->hasColumn('username', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('defaultuser', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('useragent', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('fromuser', 'string', null, array(
             'type' => 'string',
             'default' => '',
             ));
        $this->hasColumn('fromdomain', 'string', null, array(
             'type' => 'string',
             'default' => '',
             ));
        $this->hasColumn('disallow', 'string', null, array(
             'type' => 'string',
             'default' => 'all',
             ));
        $this->hasColumn('allow', 'string', null, array(
             'type' => 'string',
             'default' => 'ulaw;alaw',
             ));
        $this->hasColumn('ipaddr', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('mac', 'string', null, array(
             'type' => 'string',
             'unique' => true,
             ));
        $this->hasColumn('fullcontact', 'string', null, array(
             'type' => 'string',
             'default' => '',
             ));
        $this->hasColumn('regexten', 'string', null, array(
             'type' => 'string',
             'default' => '',
             ));
        $this->hasColumn('regserver', 'string', null, array(
             'type' => 'string',
             'default' => '',
             ));
        $this->hasColumn('regseconds', 'integer', null, array(
             'type' => 'integer',
             'default' => '0',
             ));
        $this->hasColumn('lastms', 'integer', null, array(
             'type' => 'integer',
             'default' => '0',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Rooms', array(
             'local' => 'id',
             'foreign' => 'telefon'));
    }
}