<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AsteriskVoicemail', 'hekphone');

/**
 * BaseAsteriskVoicemail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uniqueid
 * @property string $customer_id
 * @property string $context
 * @property string $mailbox
 * @property string $password
 * @property string $fullname
 * @property string $email
 * @property string $pager
 * @property string $tz
 * @property string $attach
 * @property string $saycid
 * @property string $dialout
 * @property string $callback
 * @property string $review
 * @property string $operator
 * @property string $envelope
 * @property string $sayduration
 * @property integer $saydurationm
 * @property string $sendvoicemail
 * @property string $delete
 * @property string $nextaftercmd
 * @property string $forcename
 * @property string $forcegreetings
 * @property string $hidefromdir
 * @property int $minsecs
 * @property timestamp $stamp
 * @property Doctrine_Collection $Residents
 * 
 * @method integer             getUniqueid()       Returns the current record's "uniqueid" value
 * @method string              getCustomerId()     Returns the current record's "customer_id" value
 * @method string              getContext()        Returns the current record's "context" value
 * @method string              getMailbox()        Returns the current record's "mailbox" value
 * @method string              getPassword()       Returns the current record's "password" value
 * @method string              getFullname()       Returns the current record's "fullname" value
 * @method string              getEmail()          Returns the current record's "email" value
 * @method string              getPager()          Returns the current record's "pager" value
 * @method string              getTz()             Returns the current record's "tz" value
 * @method string              getAttach()         Returns the current record's "attach" value
 * @method string              getSaycid()         Returns the current record's "saycid" value
 * @method string              getDialout()        Returns the current record's "dialout" value
 * @method string              getCallback()       Returns the current record's "callback" value
 * @method string              getReview()         Returns the current record's "review" value
 * @method string              getOperator()       Returns the current record's "operator" value
 * @method string              getEnvelope()       Returns the current record's "envelope" value
 * @method string              getSayduration()    Returns the current record's "sayduration" value
 * @method integer             getSaydurationm()   Returns the current record's "saydurationm" value
 * @method string              getSendvoicemail()  Returns the current record's "sendvoicemail" value
 * @method string              getDelete()         Returns the current record's "delete" value
 * @method string              getNextaftercmd()   Returns the current record's "nextaftercmd" value
 * @method string              getForcename()      Returns the current record's "forcename" value
 * @method string              getForcegreetings() Returns the current record's "forcegreetings" value
 * @method string              getHidefromdir()    Returns the current record's "hidefromdir" value
 * @method int                 getMinsecs()        Returns the current record's "minsecs" value
 * @method timestamp           getStamp()          Returns the current record's "stamp" value
 * @method Doctrine_Collection getResidents()      Returns the current record's "Residents" collection
 * @method AsteriskVoicemail   setUniqueid()       Sets the current record's "uniqueid" value
 * @method AsteriskVoicemail   setCustomerId()     Sets the current record's "customer_id" value
 * @method AsteriskVoicemail   setContext()        Sets the current record's "context" value
 * @method AsteriskVoicemail   setMailbox()        Sets the current record's "mailbox" value
 * @method AsteriskVoicemail   setPassword()       Sets the current record's "password" value
 * @method AsteriskVoicemail   setFullname()       Sets the current record's "fullname" value
 * @method AsteriskVoicemail   setEmail()          Sets the current record's "email" value
 * @method AsteriskVoicemail   setPager()          Sets the current record's "pager" value
 * @method AsteriskVoicemail   setTz()             Sets the current record's "tz" value
 * @method AsteriskVoicemail   setAttach()         Sets the current record's "attach" value
 * @method AsteriskVoicemail   setSaycid()         Sets the current record's "saycid" value
 * @method AsteriskVoicemail   setDialout()        Sets the current record's "dialout" value
 * @method AsteriskVoicemail   setCallback()       Sets the current record's "callback" value
 * @method AsteriskVoicemail   setReview()         Sets the current record's "review" value
 * @method AsteriskVoicemail   setOperator()       Sets the current record's "operator" value
 * @method AsteriskVoicemail   setEnvelope()       Sets the current record's "envelope" value
 * @method AsteriskVoicemail   setSayduration()    Sets the current record's "sayduration" value
 * @method AsteriskVoicemail   setSaydurationm()   Sets the current record's "saydurationm" value
 * @method AsteriskVoicemail   setSendvoicemail()  Sets the current record's "sendvoicemail" value
 * @method AsteriskVoicemail   setDelete()         Sets the current record's "delete" value
 * @method AsteriskVoicemail   setNextaftercmd()   Sets the current record's "nextaftercmd" value
 * @method AsteriskVoicemail   setForcename()      Sets the current record's "forcename" value
 * @method AsteriskVoicemail   setForcegreetings() Sets the current record's "forcegreetings" value
 * @method AsteriskVoicemail   setHidefromdir()    Sets the current record's "hidefromdir" value
 * @method AsteriskVoicemail   setMinsecs()        Sets the current record's "minsecs" value
 * @method AsteriskVoicemail   setStamp()          Sets the current record's "stamp" value
 * @method AsteriskVoicemail   setResidents()      Sets the current record's "Residents" collection
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsteriskVoicemail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asterisk_voicemail');
        $this->hasColumn('uniqueid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('customer_id', 'string', 11, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '0',
             'length' => 11,
             ));
        $this->hasColumn('context', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'default',
             'length' => 50,
             ));
        $this->hasColumn('mailbox', 'string', 11, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '0',
             'length' => 11,
             ));
        $this->hasColumn('password', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '0',
             'length' => 10,
             ));
        $this->hasColumn('fullname', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 150,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'email' => true,
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('pager', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 50,
             ));
        $this->hasColumn('tz', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'central',
             'length' => 10,
             ));
        $this->hasColumn('attach', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'yes',
             'length' => 4,
             ));
        $this->hasColumn('saycid', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'yes',
             'length' => 4,
             ));
        $this->hasColumn('dialout', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 4,
             ));
        $this->hasColumn('callback', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 10,
             ));
        $this->hasColumn('review', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'no',
             'length' => 4,
             ));
        $this->hasColumn('operator', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'no',
             'length' => 4,
             ));
        $this->hasColumn('envelope', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'no',
             'length' => 4,
             ));
        $this->hasColumn('sayduration', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'no',
             'length' => 4,
             ));
        $this->hasColumn('saydurationm', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('sendvoicemail', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'no',
             'length' => 4,
             ));
        $this->hasColumn('delete', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'no',
             'length' => 4,
             ));
        $this->hasColumn('nextaftercmd', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'yes',
             'length' => 4,
             ));
        $this->hasColumn('forcename', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'no',
             'length' => 4,
             ));
        $this->hasColumn('forcegreetings', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'no',
             'length' => 4,
             ));
        $this->hasColumn('hidefromdir', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'yes',
             'length' => 4,
             ));
        $this->hasColumn('minsecs', 'int', 2, array(
             'type' => 'int',
             'default' => 3,
             'length' => 2,
             ));
        $this->hasColumn('stamp', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Residents', array(
             'local' => 'uniqueid',
             'foreign' => 'id'));
    }
}