<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RatesRegions', 'hekphone');

/**
 * BaseRatesRegions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $rate
 * @property integer $region
 * @property Rates $Rates
 * @property Doctrine_Collection $Regions
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method integer             getRate()    Returns the current record's "rate" value
 * @method integer             getRegion()  Returns the current record's "region" value
 * @method Rates               getRates()   Returns the current record's "Rates" value
 * @method Doctrine_Collection getRegions() Returns the current record's "Regions" collection
 * @method RatesRegions        setId()      Sets the current record's "id" value
 * @method RatesRegions        setRate()    Sets the current record's "rate" value
 * @method RatesRegions        setRegion()  Sets the current record's "region" value
 * @method RatesRegions        setRates()   Sets the current record's "Rates" value
 * @method RatesRegions        setRegions() Sets the current record's "Regions" collection
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRatesRegions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rates_regions');
        $this->hasColumn('id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'rates_regions_id',
             'length' => 6,
             ));
        $this->hasColumn('rate', 'integer', 6, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             'length' => 6,
             ));
        $this->hasColumn('region', 'integer', 6, array(
             'type' => 'integer',
             'unique' => true,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rates', array(
             'local' => 'rate',
             'foreign' => 'id'));

        $this->hasMany('Regions', array(
             'local' => 'region',
             'foreign' => 'id'));
    }
}