<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AsteriskVoicemail', 'hekphone');

/**
 * BaseAsteriskVoicemail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $customer_id
 * @property string $context
 * @property integer $mailbox
 * @property string $password
 * @property string $fullname
 * @property string $email
 * @property string $pager
 * @property timestamp $stamp
 * 
 * @method integer           getId()          Returns the current record's "id" value
 * @method integer           getCustomerId()  Returns the current record's "customer_id" value
 * @method string            getContext()     Returns the current record's "context" value
 * @method integer           getMailbox()     Returns the current record's "mailbox" value
 * @method string            getPassword()    Returns the current record's "password" value
 * @method string            getFullname()    Returns the current record's "fullname" value
 * @method string            getEmail()       Returns the current record's "email" value
 * @method string            getPager()       Returns the current record's "pager" value
 * @method timestamp         getStamp()       Returns the current record's "stamp" value
 * @method AsteriskVoicemail setId()          Sets the current record's "id" value
 * @method AsteriskVoicemail setCustomerId()  Sets the current record's "customer_id" value
 * @method AsteriskVoicemail setContext()     Sets the current record's "context" value
 * @method AsteriskVoicemail setMailbox()     Sets the current record's "mailbox" value
 * @method AsteriskVoicemail setPassword()    Sets the current record's "password" value
 * @method AsteriskVoicemail setFullname()    Sets the current record's "fullname" value
 * @method AsteriskVoicemail setEmail()       Sets the current record's "email" value
 * @method AsteriskVoicemail setPager()       Sets the current record's "pager" value
 * @method AsteriskVoicemail setStamp()       Sets the current record's "stamp" value
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsteriskVoicemail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asterisk_voicemail');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'sequence' => 'asterisk_voicemail_id',
             'length' => 4,
             ));
        $this->hasColumn('customer_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('context', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('mailbox', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('password', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fullname', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pager', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('stamp', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}