<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AsteriskExtensions', 'hekphone');

/**
 * BaseAsteriskExtensions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $context
 * @property string $exten
 * @property integer $priority
 * @property string $app
 * @property string $appdata
 * 
 * @method integer            getId()       Returns the current record's "id" value
 * @method string             getContext()  Returns the current record's "context" value
 * @method string             getExten()    Returns the current record's "exten" value
 * @method integer            getPriority() Returns the current record's "priority" value
 * @method string             getApp()      Returns the current record's "app" value
 * @method string             getAppdata()  Returns the current record's "appdata" value
 * @method AsteriskExtensions setId()       Sets the current record's "id" value
 * @method AsteriskExtensions setContext()  Sets the current record's "context" value
 * @method AsteriskExtensions setExten()    Sets the current record's "exten" value
 * @method AsteriskExtensions setPriority() Sets the current record's "priority" value
 * @method AsteriskExtensions setApp()      Sets the current record's "app" value
 * @method AsteriskExtensions setAppdata()  Sets the current record's "appdata" value
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsteriskExtensions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asterisk_extensions');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'asterisk_extensions_id',
             'length' => 4,
             ));
        $this->hasColumn('context', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('exten', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('priority', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('app', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('appdata', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}