<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HekdbCurrentResidents', 'hekdb');

/**
 * BaseHekdbCurrentResidents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property integer $id
 * @property string $room_no
 * @property date $move_in
 * @property date $move_out
 * 
 * @method string                getFirstName()  Returns the current record's "first_name" value
 * @method string                getLastName()   Returns the current record's "last_name" value
 * @method integer               getId()         Returns the current record's "id" value
 * @method string                getRoomNo()     Returns the current record's "room_no" value
 * @method date                  getMoveIn()     Returns the current record's "move_in" value
 * @method date                  getMoveOut()    Returns the current record's "move_out" value
 * @method HekdbCurrentResidents setFirstName()  Sets the current record's "first_name" value
 * @method HekdbCurrentResidents setLastName()   Sets the current record's "last_name" value
 * @method HekdbCurrentResidents setId()         Sets the current record's "id" value
 * @method HekdbCurrentResidents setRoomNo()     Sets the current record's "room_no" value
 * @method HekdbCurrentResidents setMoveIn()     Sets the current record's "move_in" value
 * @method HekdbCurrentResidents setMoveOut()    Sets the current record's "move_out" value
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHekdbCurrentResidents extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('letztezimmerbelegung');
        $this->hasColumn('vorname as first_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('nachname as last_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('nutzerid as id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('zimmernummer as room_no', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('einzug as move_in', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('auszug as move_out', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}