<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Prefixes', 'hekphone');

/**
 * BasePrefixes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $prefix
 * @property string $name
 * @property integer $region
 * @property Regions $Regions
 * 
 * @method integer  getId()      Returns the current record's "id" value
 * @method string   getPrefix()  Returns the current record's "prefix" value
 * @method string   getName()    Returns the current record's "name" value
 * @method integer  getRegion()  Returns the current record's "region" value
 * @method Regions  getRegions() Returns the current record's "Regions" value
 * @method Prefixes setId()      Sets the current record's "id" value
 * @method Prefixes setPrefix()  Sets the current record's "prefix" value
 * @method Prefixes setName()    Sets the current record's "name" value
 * @method Prefixes setRegion()  Sets the current record's "region" value
 * @method Prefixes setRegions() Sets the current record's "Regions" value
 * 
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrefixes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('prefixes');
        $this->hasColumn('id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'prefixes_id',
             'length' => 6,
             ));
        $this->hasColumn('prefix', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('region', 'integer', 6, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Regions', array(
             'local' => 'region',
             'foreign' => 'id'));
    }
}