<?php

/**
 * AgencysTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgencysTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgencysTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Agencys');
    }
}