<?php

/**
 * AsteriskSipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsteriskSipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsteriskSipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsteriskSip');
    }
}