<?php

/**
 * AsteriskExtensionsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsteriskExtensionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsteriskExtensionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsteriskExtensions');
    }

    /**
     * The function updates/creates the extension neccesary to dial to the sip
     * phone of a user.
     *
     * The extensions are generated in the context 'phones' which can be
     * included in the context 'locked' and 'unlocked' and 'amt' (which is
     * what you reach if you call from outside)
     *
     * @param integer $extension
     * @param integer $residentid
     * @return string
     */
    public function updateResidentsExtension(Residents $resident)
    {
        $extensionPrefix = '_8695';
        if ( ! $extension = "1" . $resident['Rooms']['room_no']) {
          sfContext::getInstance()->getLogger()->warning('Tried to update extension of a resident ' . $residentid . ' not living in a room. Extension not updated.');
          return false;
        }
        $phone     = Doctrine_Core::getTable('Phones')->findOneByName($extension);
        $context   = ($resident['unlocked'])? 'unlocked' : 'locked';


        // Merciless delete any old entries of the room/phone: //
        $this->createQuery()
           ->delete()
           ->where('exten = ?', $extensionPrefix . $extension)
           ->execute();

        // Prepare the extensions entries: //
        // call the phone located in the room
        $arrayExtensions[0] = array(
             'exten'        => $extensionPrefix . $extension,
             'priority'     => 1,
             'context'      => $context,
             'app'          => 'Dial',
        );
        if ($resident['vm_active']) {
            // in case the voicemail is activated, only ring for a specified number
            // of times
            $arrayExtensions[0]['appdata'] = $phone['technologie'] . '/' . $extension
                                           . '|' . $resident['vm_seconds'];
        } else {
            // if not, ring until the caller hangs up
            $arrayExtensions[0]['appdata'] = $phone['technologie'] . '/' . $extension;
        }

        // include forwarding to mailbox if it's active
        // this is resident specific so only insert it if
        // there's a residentid provided
        $vm_active = true;
        if ($resident['vm_active'])
        {
            $arrayExtensions[1] = array(
                'exten'        => $extensionPrefix . $extension,
                'priority'     => 2,
                'context'      => $context,
                'app'          => 'Voicemail',
                'appdata'      => $resident->id . '@default'
            );
        }

        // hangup after the call finished
        $arrayExtensions[2] = array(
            'exten'        => $extensionPrefix . $extension,
            'priority'     => 99,
            'context'      => $context,
            'app'          => 'Hangup',
            'appdata'      => ''
        );

        // Insert the new extension in the database: //
        $collExtensions = Doctrine_Collection::create('AsteriskExtensions');
        $collExtensions->fromArray($arrayExtensions);
        $collExtensions->save();

        return true;
    }
}