<?php

/**
 * AsteriskCdrTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsteriskCdrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsteriskCdrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsteriskCdr');
    }

    /**
     * find all calls in AsteriskCdr which are not marked as billed
     * (AsteriskCdr.billed = false) in period of time
     *
     * @param date $from  start of the timeperiod
     * @param date $to    end of the timeperiod
     * @return DoctrineCollection
     */
    function findUnallocatedCalls($from, $to) {
        $q = Doctrine_Query::create()
            ->from('AsteriskCdr c')
            ->addWhere('c.billed = false')
            ->addWhere("c.calldate >= '$from'")
            ->addwhere("c.calldate <= '$to'")
            ->addWhere("c.disposition = 'ANSWERED'")
            ->andWhereNotIn("c.dcontext", sfConfig::get('asteriskIncomingContext'));
         return $q->execute();
    }
}