<?php

/**
 * AsteriskVoicemailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsteriskVoicemailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsteriskVoicemailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsteriskVoicemail');
    }
}