<?php

/**
 * AsteriskCdrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsteriskCdrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsteriskCdrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsteriskCdr');
    }
}