<?php

/**
 * AsteriskExtensionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsteriskExtensionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsteriskExtensionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsteriskExtensions');
    }
}