<?php

/**
 * BanksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BanksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BanksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Banks');
    }
}