<?php

/**
 * BillsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bills');
    }
}