<?php

/**
 * GroupcallsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupcallsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupcallsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Groupcalls');
    }
}