<?php

/**
 * Groupcalls
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    hekphone
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Groupcalls extends BaseGroupcalls
{
  public function getExtensionsAsArray() {
    $context = 'groupcalls';
    $phonesList = '';
    foreach($this->Residents as $Resident) {
        if($Resident->Rooms->Phones->get('technology') == 'DAHDI/g1')
        {
          $prefix = '86951';
        } else {
          $prefix = '1';
        }

        $phonesList .= $Resident->Rooms->Phones->get('technology') . '/' . $prefix . $Resident->Rooms . ASTERISK_PARAMETER_SEPARATOR;
        ;
    }
    $phonesList = substr($phonesList, 0, -1 * strlen(ASTERISK_PARAMETER_SEPARATOR)); //strip the last parameter separator

    $arrayExtensions[0] = array(
         'exten'        => $this->extension,
         'priority'     => 1,
         'context'      => $context,
         'app'          => 'Dial',
         'appdata'      => $phonesList
    );
    $arrayExtensions[1] = array(
         'exten'        => $this->extension,
         'priority'     => 1,
         'context'      => $context,
         'app'          => 'Hangup',
    );

    return $arrayExtensions;
  }
}
