<?php

/**
 * HekdbCurrentResidentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HekdbCurrentResidentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HekdbCurrentResidentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HekdbCurrentResidents');
    }
}