<?php

/**
 * PhonesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhonesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhonesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Phones');
    }

    /**
     * Finds a phone belonging to a resident $resident. Only returns
     * a Phone if the resident still lives in the dormitory.
     *
     * @param Residents $resident
     * @return Phones
     */
    public function findByResident($resident)
    {
        if( ! $resident || ! $resident->isStillLivingHere()) {
          return false;
        }

        if ( $resident['Rooms']->phone == NULL ) {
            return false;
        } else {
            return Doctrine_Core::getTable('Phones')->findOneById($resident['Rooms']->phone);
        }
    }

    /**
     * Finds a phone belonging to a resident with id $residentid . Only returns
     * a Phone if the resident still lives in the dormitory
     *
     * @param integer $residentid
     * @return Phones
     */
    public function findByResidentId($residentid)
    {
        $resident = Doctrine_Core::getTable('Residents')->findOneById($residentid);
        if( ! $resident || ! $resident->isStillLivingHere()) {
          return false;
        }

        if ( $resident['Rooms']->phone == NULL ) {
            return false;
        } else {
            return Doctrine_Core::getTable('Phones')->findOneById($resident['Rooms']->phone);
        }
    }

    public function findByRoomNo($roomNo)
    {
        $room = Doctrine_Core::getTable('Rooms')->findOneBy('room_no', $roomNo);
        if ( $room['phone'] == NULL ) {
            return false;
        } else {
            return Doctrine_Core::getTable('Phones')->findOneById($room['phone']);
        }
    }
}