<?php

/**
 * PhonesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhonesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhonesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Phones');
    }

    public function findByResidentId($resident)
    {
        if ( ! $resident = Doctrine_Core::getTable('Residents')->findOneById($resident))
        {
            return false;
        }
        else
        {
            return Doctrine_Core::getTable('Phones')->findOneById($resident['Rooms']->phone);
        }
    }
    public function findByRoomNo($roomNo)
    {
        //TODO: implement this
    }
}