<?php

/**
 * PhonesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhonesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhonesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Phones');
    }

    public function findByResidentId($resident)
    {
        $resident = Doctrine_Core::getTable('Residents')->findOneById($resident);
        if ( $resident['Rooms']->phone == NULL )
        {
            return false;
        }
        else
        {
            return Doctrine_Core::getTable('Phones')->findOneById($resident['Rooms']->phone);
        }
    }

    public function findByRoomNo($roomNo)
    {
        $room = Doctrine_Core::getTable('Rooms')->findOneBy('room_no', $roomNo);
        if ( $room['phone'] == NULL )
        {
            return false;
        }
        else
        {
            return Doctrine_Core::getTable('Phones')->findOneById($room['phone']);
        }
    }
}