<?php

/**
 * ProvidersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProvidersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProvidersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Providers');
    }
}