<?php

/**
 * RatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rates');
    }
}