<?php

/**
 * RatesRegionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RatesRegionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RatesRegionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RatesRegions');
    }
}