<?php

/**
 * ResidentsGroupcallsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResidentsGroupcallsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResidentsGroupcallsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResidentsGroupcalls');
    }
}