<?php

/**
 * RoomsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoomsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoomsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rooms');
    }
}